name: Publish nf-core to PyPI
on:
  release:
    types: [published]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        name: Check out source-code repository

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip build
          pip install .

      - name: Build the binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish dist to PyPI
        if: github.repository == 'qbic-pipelines/querynator'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
